In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
a

In [ ]:
b = np.array([[3.0,5.0, 1.0],[9.0,2.0,3.0]],dtype='float32')
b

In [ ]:
# Get dimension
# Get type
# Get shape

a.ndim, b.dtype, b.shape


In [32]:
# Get size of each item, in bytes
# Get size of array, in data points
# Get total size in bytes
b.itemsize, b.size, b.nbytes

(4, 6, 24)

In [37]:
# Define a 2d array
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])


In [40]:
# Get a specific element [r,c]
a[1, 5]

np.int64(13)

In [42]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [44]:
# Get a specific column
a[:,3]

array([ 4, 11])

In [46]:
# More advanced [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [50]:
# Change elements
a[1,5] = 20
# Replace column
a[:,2] = [9,9]
a

array([[ 1,  2,  9,  4,  5,  6,  7],
       [ 8,  9,  9, 11, 12, 20, 14]])

In [53]:
# 3D example
b = np.array([[[1,2],[3,4]],[[3,5],[6,8]]])
b.shape

(2, 2, 2)

In [55]:
# Get an element in 3D
b[1,0,1]

np.int64(5)

In [57]:
b[:,1,:]

array([[3, 4],
       [6, 8]])

In [ ]:
b[:,1,:] = [[1,1],[1,1]]
b

In [67]:
# Initialize all 0 array
np.zeros((2,3,2))
# Can do np.ones
np.ones((2,2,2), dtype='int16')
# Also any other number
np.full((3,2),11)

array([[11, 11],
       [11, 11],
       [11, 11]])

In [108]:
# Full_like, imitates a shape and fills another array in that shape
np.full_like(a,3)

array([3, 3, 3])

In [130]:
# Random decimals
np.random.rand(3,4)
# Random imitating a shape
np.random.random_sample(a.shape)

array([[0.35707274, 0.15931568, 0.47572652],
       [0.00710586, 0.24714098, 0.10629737]])

In [106]:
np.random.randint(7, size = (3,3,3))

array([[[3, 0, 0],
        [1, 6, 5],
        [3, 2, 3]],

       [[6, 5, 3],
        [4, 0, 2],
        [4, 5, 6]],

       [[4, 6, 1],
        [6, 2, 5],
        [6, 3, 5]]], dtype=int32)

In [118]:
# Repeating an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [117]:
examplefollowing = np.ones((5,5),dtype='int8')
examplefollowing[1:4,1:4] = np.full((3,3),0,dtype='int8')
examplefollowing[2,2] = 9
print(examplefollowing.nbytes)
print(examplefollowing)


25
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [120]:
a = np.array([1,2,3])
# b = a <-- this would point b to a, not copy it
b = a.copy() # <-- correct
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


MATH STARTS HERE

In [123]:

c = np.array([1,2,3,4,5])
print(c)
print(c + 2) # adds this value to all within the array
print(c - 2) # Same as addition
print(c * 2) # ^
print(c / 2) # ^
# Other operations are the same, such as exp, sin, sqrt, etc.


[1 2 3 4 5]
[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [132]:
# Linear algebra basics
a = np.ones((2,3),dtype='int8')
b = np.full((3,2),2)
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [139]:
c = np.identity(2)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
# Statistics
stats = np.array([[1,2,3],[3,5,6]])
stats

array([[1, 2, 3],
       [3, 5, 6]])

In [141]:
np.min(stats)

np.int64(1)

In [144]:
print(np.max(stats))
print(np.max(stats, axis=0)) # Can be used to find the max row or column

6
[3 5 6]


In [147]:
print(np.sum(stats))
print(np.sum(stats,axis=1))

20
[ 6 14]


In [151]:
# Reorganizing Arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.reshape((8,1)))
print(before.reshape((2,2,2)))

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [154]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [156]:
# Horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [161]:
# Loading from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int16')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [165]:
# Boolean masking and advanced indexing
filedata > 50
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int16)

In [ ]:
np.any(filedata > 50, axis = 0) # If any value in the column is greater than 50
# np.all is the same, but requires all values to meet the condition

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [170]:
(((filedata > 50) & (filedata < 100)))
(~((filedata > 50) & (filedata < 100))) # The ~ makes it "not"
 

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
a = np.arange(10,50) # Arange fills an array with numbers between first arg and second arg.
a = a[::-1] # Reverses array
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
a = np.eye(3) # Identity matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
z = np.ones((9,9))
z[1:-1,1:-1] = 0 # Forms a border
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [187]:
z = np.ones((9,9))
z = np.pad(z, pad_width=2)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

nan
False
False
nan
True
False
